### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by rollback91** [openscienceschool/di-lambda#1]
Hi there, I was wondering if it was possible to share the schematics as well.

Thanks

**Comment by xl0** [comment]
Heya,

I meant to clean it up and add to this repo, but never got to doing it. 
If you'd like to have a look at the current state of affairs: https://github.com/koi-science/DI-Lambda-schematics-avr . It's been STM32 for a long time though, not AVR, I just did not rename the repo.

Just pushed all I had, if any files are missing or something does not open, please let me know.

**Comment by rollback91** [comment]
Thanks, a lot! I'll update you if something is broken!
